# Generated by Django 5.0.4 on 2024-05-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_myuser_is_customer_myuser_is_staff_member_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
